version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CLICKUP_API_KEY=${CLICKUP_API_KEY}
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
