site_name: CLICKUPAPI DOCUMENTATION
nav:
  - Início: index.pt.md
  - API: api.pt.md
  - Backup: backup.pt.md
  - Docker: docker.pt.md
  - Principal: main.pt.md
  - Redis: redis.pt.md
  - Renderizar: render.pt.md
  - Rotas: routes.pt.md
  - Testes: tests.pt.md
  - Utilidades: utils.pt.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
theme:
  name: material
  language: pt
