site_name: CLICKUPAPI DOCUMENTATION
nav:
  - Home: index.md
  - API: api.md
  - Bakcup: backup.md
  - Docker: docker.md
  - Main: main.md
  - Redis: redis.md
  - Render: render.md
  - Routes: routes.md
  - Tests: tests.md
  - Utils: utils.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
theme:
  name: material
