[tool.poetry]
name = "myfastapiapp"
version = "0.1.0"
description = "A FastAPI application to interact with ClickUp API"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
fastapi = "^0.95.2"
httpx = "^0.24.1"
pandas = "^2.0.1"
numpy = "^1.24.3"
requests = "^2.31.0"
openpyxl = "^3.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
