name: Schedule and Push API Requests

on:
  # Executa a cada 3 horas
  schedule:
    - cron: '0 */3 * * *'  # Executa a cada 3 horas
  
  # Executa sempre que houver uma mudança no repositório
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar, por exemplo, 'main'

jobs:
  call_apis:
    runs-on: ubuntu-latest

    steps:
    - name: Make API request to get_data_organized/192959544
      run: |
        echo "Fetching: ${{ secrets.API_URL_1_INO }}"
        curl -s -o /dev/null -w "%{http_code}" "${{ secrets.API_URL_1_INO }}"
        if [ $? -ne 0 ]; then
          echo "Failed to fetch ${{ secrets.API_URL_1_INO }}"
          exit 1
        fi

    - name: Make API request to get_data_organized/174940580
      run: |
        echo "Fetching: ${{ secrets.API_URL_2_NEG }}"
        curl -s -o /dev/null -w "%{http_code}" "${{ secrets.API_URL_2_NEG }}"
        if [ $? -ne 0 ]; then
          echo "Failed to fetch ${{ secrets.API_URL_2_NEG }}"
          exit 1
        fi
