name: Schedule API Requests

on:
  schedule:
    - cron: '0 */3 * * *'  # Executa a cada 3 horas

jobs:
  call_apis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up shell script permissions
      run: chmod +x ./run_api_requests.sh

    - name: Make API requests
      run: ./run_api_requests.sh "${{ secrets.API_URL_1_INO }}" "${{ secrets.API_URL_2_NEG }}"
